version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "4000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge
