version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "4000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
